In [1]:
%reload_ext autoreload
%autoreload 2

In [2]:
import torch

In [9]:
s = torch.arange(0, 5000).unsqueeze(1)

In [13]:
torch.exp??

Docstring:
exp(input, out=None) -> Tensor

Returns a new tensor with the exponential of the elements
of the input tensor :attr:`input`.

.. math::
    y_{i} = e^{x_{i}}

Args:
    input (Tensor): the input tensor.
    out (Tensor, optional): the output tensor.

Example::

    >>> torch.exp(torch.tensor([0, math.log(2.)]))
    tensor([ 1.,  2.])
Type:      builtin_function_or_method


In [30]:
torch.exp(torch.tensor(math.log(1e+7)))

tensor(9999997.)

In [31]:
div_term = torch.exp(torch.arange(0, 756, 2) *
                     -(math.log(10000.0) / 756))

In [32]:
div_term[:30]

tensor([1.0000, 0.9759, 0.9524, 0.9295, 0.9071, 0.8853, 0.8640, 0.8432, 0.8229,
        0.8031, 0.7838, 0.7649, 0.7465, 0.7285, 0.7110, 0.6939, 0.6772, 0.6609,
        0.6449, 0.6294, 0.6143, 0.5995, 0.5851, 0.5710, 0.5572, 0.5438, 0.5307,
        0.5179, 0.5055, 0.4933])

In [41]:
div_term2 = torch.exp(-torch.arange(0, 756, 2)*(9/756))

In [36]:
math.log(1e+4)

9.210340371976184

In [40]:
div_term2[:30]

tensor([1.0000, 0.9765, 0.9535, 0.9311, 0.9092, 0.8878, 0.8669, 0.8465, 0.8266,
        0.8071, 0.7881, 0.7696, 0.7515, 0.7338, 0.7165, 0.6997, 0.6832, 0.6671,
        0.6514, 0.6361, 0.6211, 0.6065, 0.5923, 0.5783, 0.5647, 0.5514, 0.5385,
        0.5258, 0.5134, 0.5013])